apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloservice
  template:
    metadata:
      labels:
        app: helloservice
    spec:
      containers:
        - image: hashicorp/http-echo
          args:
            - "-text=Hello from HelloService!"
          imagePullPolicy: IfNotPresent
          name: helloservice
          ports:
            - containerPort: 5678
      restartPolicy: Always
